# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20161105_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrics',
            old_name='wow_status',
            new_name='row_status',
        ),
    ]
